// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.ResourceAccess.Model
{

    // SalesTerritory
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class Sales_SalesTerritoryConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Sales_SalesTerritory>
    {
        public Sales_SalesTerritoryConfiguration()
            : this("Sales")
        {
        }

        public Sales_SalesTerritoryConfiguration(string schema)
        {
            Property(x => x.SalesYtd).HasPrecision(19,4);
            Property(x => x.SalesLastYear).HasPrecision(19,4);
            Property(x => x.CostYtd).HasPrecision(19,4);
            Property(x => x.CostLastYear).HasPrecision(19,4);

        }
    }

}
// </auto-generated>
